apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openapi-service-template.fullname" . }}-config
  labels:
    {{- include "openapi-service-template.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
